# Basic OpenDKIM configuration
Canonicalization     relaxed/simple
Mode                 sv
SubDomains           no
AutoRestart          yes
AutoRestartRate      10/1M
Background           yes
DNSTimeout           5
SignatureAlgorithm   rsa-sha256

# Socket configuration
Socket               inet:8891

# OpenDKIM user
UserID               opendkim

# Map domains in From addresses to keys used to sign messages
KeyTable             refile:/etc/opendkim/KeyTable
SigningTable         refile:/etc/opendkim/SigningTable

# Hosts to ignore when verifying signatures
ExternalIgnoreList   /etc/opendkim/TrustedHosts
InternalHosts        /etc/opendkim/TrustedHosts

# Logging
LogWhy               yes
Syslog               yes
SyslogSuccess        yes
